export const INIT_DATA = 'INIT_DATA';
export const RECORD_DATA = 'RECORD_DATA';
export const PRIZE_DATA = 'PRIZE_DATA';
export const SHARE_TASK = 'SHARE_TASK';
export const VIDEO_PRIZE = 'VIDEO_PRIZE'; //看视频所得奖品
export const SHOW_LOGIN_TOAST = 'SHOW_LOGIN_TOAST'; //显示去登录弹窗
export const SHOW_GET_CARD_LIST = 'SHOW_GET_CARD_LIST'; //显示得卡明细弹窗
export const SHOW_DIALOG = 'SHOW_DIALOG'; //显示弹窗
export const HIDE_DIALOG = 'HIDE_DIALOG'; //隐藏弹窗
export const COMMPOP_DATA = 'COMMPOP_DATA'; //通用弹窗数据
export const CARDPOP_DATA = 'CARDPOP_DATA'; //得卡弹窗数据
export const DETAIL_INDEX = 'DETAIL_INDEX'; //【卡片详情】显示索引
export const DETAIL_SHOW = 'DETAIL_SHOW'; //【卡片详情】显隐
export const RECORD_RELOAD = 'RECORD_RELOAD'; //得卡明细页“重新加载”，显隐
export const SHOW_LOWVERSION = 'SHOW_LOWVERSION'; //低版本提示弹窗，显隐
export const NO_MOVE = 'NO_MOVE'; //禁止页面滚动
export const YES_MOVE = 'YES_MOVE'; //可以页面滚动
export const SAFE_TIP = 'SAFE_TIP'; //不安全提示弹窗，显隐
export const DUROPENTIME = 'DUROPENTIME'; //计算出当前时间距离开奖时间的时间差
export const DURENDTIME = 'DURENDTIME'; //计算出当前时间距离开奖结束时间的时间差
export const UPDATE_ROLES = 'UPDATE_ROLES'; //更新卡包
export const LIGHT_TIP = 'LIGHT_TIP'; //轻提示弹窗，显隐
export const SHOW_MASKER = 'SHOW_MASKER'; //轻提示弹窗，显隐
export const SHOW_ME = 'SHOW_ME'; //轻提示弹窗，显隐
