/*{"created":"2010-08-25T22:34:12Z","k":"0.7.11","mac":"1:31237d50ccf4583a364508fba9d26ebce5e165e85c1a453bd838e1532324a147","version":"730594"}*/
;(function(window,document,undefined){
function g(a){return function(){return this[a]}}var h;function j(a,b){this.n=a;this.e=b}h=j.prototype;h.createElement=function(a,b,c){a=this.n.createElement(a);if(b)for(var d in b)if(b.hasOwnProperty(d))if(d=="style"&&this.e.getName()=="MSIE")a.style.cssText=b[d];else a.setAttribute(d,b[d]);c&&a.appendChild(this.n.createTextNode(c));return a};h.insertInto=function(a,b){a=this.n.getElementsByTagName(a)[0];if(!a)a=document.documentElement;if(a&&a.lastChild){a.insertBefore(b,a.lastChild);return true}return false};
h.removeElement=function(a){if(a.parentNode){a.parentNode.removeChild(a);return true}return false};h.createCssLink=function(a){return this.createElement("link",{rel:"stylesheet",href:a})};h.appendClassName=function(a,b){for(var c=a.className.split(/\s+/),d=0,e=c.length;d<e;d++)if(c[d]==b)return;c.push(b);a.className=c.join(" ").replace(/^\s+/,"")};
h.removeClassName=function(a,b){for(var c=a.className.split(/\s+/),d=[],e=0,f=c.length;e<f;e++)c[e]!=b&&d.push(c[e]);a.className=d.join(" ").replace(/^\s+/,"").replace(/\s+$/,"")};function m(a,b,c,d,e,f,i){this.ba=a;this.ka=b;this.W=c;this.V=d;this.ea=e;this.da=f;this.la=i}h=m.prototype;h.getName=g("ba");h.getVersion=g("ka");h.getEngine=g("W");h.getEngineVersion=g("V");h.getPlatform=g("ea");h.getPlatformVersion=g("da");function o(a){this.e=a}
var p=new m("Unknown","Unknown","Unknown","Unknown","Unknown","Unknown",false);o.prototype.parse=function(){return this.e.indexOf("MSIE")!=-1?aa(this):this.e.indexOf("Opera")!=-1?ba(this):this.e.indexOf("AppleWebKit")!=-1?ca(this):this.e.indexOf("Gecko")!=-1?da(this):p};function q(a){var b=r(a,a.e,/(iPod|iPad|iPhone|Android)/,1);if(b!="")return b;a=r(a,a.e,/(Linux|Mac_PowerPC|Macintosh|Windows)/,1);if(a!=""){if(a=="Mac_PowerPC")a="Macintosh";return a}return"Unknown"}
function s(a){var b=r(a,a.e,/(OS X|Windows NT|Android) ([^;]+)/,2);if(b)return b;if(b=r(a,a.e,/(iPhone )?OS ([\d_]+)/,2))return b;if(a=r(a,a.e,/Linux ([i\d]+)/,1))return a;return"Unknown"}function aa(a){var b=r(a,a.e,/(MSIE [\d\w\.]+)/,1);if(b!=""){var c=b.split(" ");b=c[0];c=c[1];return new m(b,c,b,c,q(a),s(a),t(a,c)>=6)}return new m("MSIE","Unknown","MSIE","Unknown",q(a),s(a),false)}
function ba(a){var b="Unknown",c="Unknown",d=r(a,a.e,/(Presto\/[\d\w\.]+)/,1);if(d!=""){c=d.split("/");b=c[0];c=c[1]}else{if(a.e.indexOf("Gecko")!=-1)b="Gecko";d=r(a,a.e,/rv:([^\)]+)/,1);if(d!="")c=d}if(a.e.indexOf("Version/")!=-1){d=r(a,a.e,/Version\/([\d\.]+)/,1);if(d!="")return new m("Opera",d,b,c,q(a),s(a),t(a,d)>=10)}d=r(a,a.e,/Opera[\/ ]([\d\.]+)/,1);if(d!="")return new m("Opera",d,b,c,q(a),s(a),t(a,d)>=10);return new m("Opera","Unknown",b,c,q(a),s(a),false)}
function ca(a){var b=q(a),c=s(a),d=r(a,a.e,/AppleWebKit\/([\d\.\+]+)/,1);if(d=="")d="Unknown";var e="Unknown";if(a.e.indexOf("Chrome")!=-1)e="Chrome";else if(a.e.indexOf("Safari")!=-1)e="Safari";var f="Unknown";if(a.e.indexOf("Version/")!=-1)f=r(a,a.e,/Version\/([\d\.\w]+)/,1);else if(e=="Chrome")f=r(a,a.e,/Chrome\/([\d\.]+)/,1);var i=r(a,d,/\d+\.(\d+)/,1);return new m(e,f,"AppleWebKit",d,b,c,t(a,d)>=526||t(a,d)>=525&&parseInt(i,10)>=13)}
function da(a){var b="Unknown",c="Unknown",d=false;if(a.e.indexOf("Firefox")!=-1){b="Firefox";var e=r(a,a.e,/Firefox\/([\d\w\.]+)/,1);if(e!=""){d=r(a,e,/\d+\.(\d+)/,1);c=e;d=e!=""&&t(a,e)>=3&&parseInt(d,10)>=5}}else if(a.e.indexOf("Mozilla")!=-1)b="Mozilla";e=r(a,a.e,/rv:([^\)]+)/,1);if(e=="")e="Unknown";else if(!d){d=t(a,e);var f=parseInt(r(a,e,/\d+\.(\d+)/,1),10),i=parseInt(r(a,e,/\d+\.\d+\.(\d+)/,1),10);d=d>1||d==1&&f>9||d==1&&f==9&&i>=2||e.match(/1\.9\.1b[123]/)!=null||e.match(/1\.9\.1\.[\d\.]+/)!=
null}return new m(b,c,"Gecko",e,q(a),s(a),d)}function t(a,b){a=r(a,b,/(\d+)/,1);if(a!="")return parseInt(a,10);return-1}function r(a,b,c,d){if((a=b.match(c))&&a[d])return a[d];return""}function ea(a,b,c,d){this.g=a;this.j=b;this.H=c;this.m=d||fa;this.l=new u("-")}var fa="wf";function v(a,b,c){a.g.removeClassName(a.j,a.l.k(a.m,b,c,"loading"));a.g.appendClassName(a.j,a.l.k(a.m,b,c,"active"));x(a,"fontactive",b,c)}function z(a){a.g.appendClassName(a.j,a.l.k(a.m,"inactive"));x(a,"inactive")}
function ga(a){a.g.removeClassName(a.j,a.l.k(a.m,"loading"));a.g.appendClassName(a.j,a.l.k(a.m,"active"));x(a,"active")}function x(a,b,c,d){a.H[b]&&a.H[b](c,d)}function A(a,b,c,d,e){this.g=a;this.p=b;this.B=c;this.w=d;this.M=e;this.I=0;this.F=this.P=false;this.aa=new B;this.X=new C}
A.prototype.watch=function(a,b,c){for(var d=a.length,e=0;e<d;e++){var f=a[e];b[f]||(b[f]=["n4"]);this.I+=b[f].length}if(c)this.P=c;for(e=0;e<d;e++){f=a[e];c=b[f];for(var i=0,y=c.length;i<y;i++){var k=c[i],n=D(this,"_,arial,helvetica",k),w=this.B.C(n);this.g.removeElement(n);n=f;var l=this.p;l.g.appendClassName(l.j,l.l.k(l.m,n,k,"loading"));x(l,"fontloading",n,k);l=D(this,this.aa.quote(n),k);if(w!=this.B.C(l)){this.g.removeElement(l);v(this.p,n,k);this.F=true;E(this)}else F(this,this.M(),w,l,n,k)}}};
function E(a){if(--a.I==0&&a.P)a.F?ga(a.p):z(a.p)}A.prototype.U=function(a,b,c,d,e){if(b!=this.B.C(c)){this.g.removeElement(c);v(this.p,d,e);this.F=true;E(this)}else if(this.M()-a<5E3)F(this,a,b,c,d,e);else{this.g.removeElement(c);a=this.p;a.g.removeClassName(a.j,a.l.k(a.m,d,e,"loading"));a.g.appendClassName(a.j,a.l.k(a.m,d,e,"inactive"));x(a,"fontinactive",d,e);E(this)}};function F(a,b,c,d,e,f){a.w(function(i,y){return function(){y.call(i,b,c,d,e,f)}}(a,a.U),50)}
function D(a,b,c){c=a.X.expand(c);b=a.g.createElement("span",{style:"position:absolute;top:-999px;font-size:300px;font-family:"+b+",_,arial,helvetica;"+c},"Mm");a.g.insertInto("body",b);return b}function u(a){this.Z=a||ha}var ha="-";u.prototype.k=function(){for(var a=[],b=0;b<arguments.length;b++)a.push(arguments[b].replace(/[\W_]+/g,"").toLowerCase());return a.join(this.Z)};function B(){this.S='"'}
B.prototype.quote=function(a){var b=[];a=a.split(/,\s*/);for(var c=0;c<a.length;c++){var d=a[c].replace(/['"]/g,"");d.indexOf(" ")==-1?b.push(d):b.push(this.S+d+this.S)}return b.join(",")};function C(){this.R=ia;this.s=ja}var ia=["font-style","font-weight"],ja={"font-style":[["n","normal"],["i","italic"],["o","oblique"]],"font-weight":[["1","100"],["2","200"],["3","300"],["4","400"],["5","500"],["6","600"],["7","700"],["8","800"],["9","900"],["4","normal"],["7","bold"]]};
function G(a,b,c){this.Y=a;this.fa=b;this.s=c}G.prototype.expand=function(a,b){for(var c=0;c<this.s.length;c++)if(b==this.s[c][0]){a[this.Y]=this.fa+":"+this.s[c][1];return}};C.prototype.expand=function(a){if(a.length!=2)return null;for(var b=[null,null],c=0,d=this.R.length;c<d;c++){var e=this.R[c],f=a.substr(c,1);(new G(c,e,this.s[e])).expand(b,f)}return b[0]&&b[1]?b.join(";")+";":null};function H(a,b){this.n=a;this.e=b}H.prototype=j.prototype;
H.prototype.isHttps=function(){return this.n.location.protocol=="https:"};H.prototype.loadScript=function(a,b){var c=this.n.getElementsByTagName("head")[0];if(c){var d=this.n.createElement("script");d.src=a;var e=false;d.onload=d.onreadystatechange=function(){if(!e&&(!this.readyState||this.readyState=="loaded"||this.readyState=="complete")){e=true;b&&b();d.onload=d.onreadystatechange=null;d.parentNode.tagName=="HEAD"&&c.removeChild(d)}};c.appendChild(d)}};
H.prototype.createStyle=function(a){var b=this.n.createElement("style");b.setAttribute("type","text/css");if(b.styleSheet)b.styleSheet.cssText=a;else b.appendChild(document.createTextNode(a));return b};function ka(a){for(var b=a.ia.join(","),c=[],d=0;d<a.J.length;d++){var e=a.J[d];c.push(e.name+":"+e.value+";")}return b+"{"+c.join("")+"}"}function I(a,b){this.t=a;this.K=b}I.prototype.watch=function(a,b,c){var d=[],e={};d.push(this.t);e[this.t]=this.K[b.getStylesheetFormatId()]||[];a.watch(d,e,c)};
function J(a,b,c){this.ja=a;this.D=b;this.ga=c}J.prototype.buildUrl=function(a,b){a=this.ja&&a?"https:":"http:";var c=typeof this.D=="function"?this.D(a):this.D;return a+"//"+c+this.ga+b};function la(a,b,c){if(a.L){var d=function(){try{b._gat._getTracker("UA-8850781-3")._trackPageview();b.tkKitsTracked||(b.tkKitsTracked=0);b.tkKitsTracked++}catch(e){}};if(b._gat)d();else{a=a.L.buildUrl(c.isHttps(),"/ga.js");c.loadScript(a,d)}}}function K(a,b,c){this.r=a;this.T=b;this.O=c}K.prototype.getId=g("r");
K.prototype.getStylesheetFormatId=g("T");K.prototype.isUserAgent=function(a){return this.O?this.O(a.getName(),a.getVersion(),a.getEngine(),a.getEngineVersion(),a.getPlatform(),a.getPlatformVersion()):false};K.prototype.buildCssUrl=function(a,b,c,d){c="/"+c+"-"+this.T+".css";if(d)c+="?"+d;return b.buildUrl(a,c)};function L(){this.o=[]}L.prototype.h=function(a){M(this,a.getId())||this.o.push(a)};function M(a,b){for(var c=0;c<a.o.length;c++){var d=a.o[c];if(b===d.getId())return d}return null}
function N(a,b){for(var c=0;c<a.o.length;c++){var d=a.o[c];if(d.isUserAgent(b))return d}return null}L.prototype.addBrowsersToBrowserSet=function(a){for(var b=0;b<this.o.length;b++)a.h(this.o[b])};function O(a){this.r=a;this.z=new L;this.q=[];this.A=[]}h=O.prototype;h.getId=g("r");h.h=function(a){this.z.h(a)};h.supportsBrowser=function(a){return!!M(this.z,a.getId())};h.addBrowsersToBrowserSet=function(a){this.z.addBrowsersToBrowserSet(a)};
h.init=function(a){for(var b=[],c=0;c<this.A.length;c++)b.push(ka(this.A[c]));a.insertInto("head",a.createStyle(b.join("")))};h.load=function(a,b,c,d){var e=c.buildCssUrl(a.isHttps(),this.ca,this.r,this.ha);a.insertInto("head",a.createCssLink(e));if(b)for(a=0;a<this.q.length;a++)this.q[a].watch(b,c,d&&a==this.q.length-1)};
h.performOptionalActions=function(a,b,c){if(this.u){la(this.u,a,c);a=this.u;var d=this.r;if(a.Q){a=a.Q.buildUrl(c.isHttps(),"/"+d+".js?"+ +new Date);c.loadScript(a)}d=this.u;a=this.r;if(d.G){b=d.G.k(a,b,c);b.setAttribute("id","typekit-badge-"+a);c.insertInto("body",b)}}};function P(a,b,c,d,e){this.$=a;this.g=b;this.e=c;this.j=d;this.w=e;this.i=[]}P.prototype.v=function(a){this.i.push(a)};
P.prototype.load=function(a,b){a=a;var c=b||{};if(typeof a=="string")a=[a];else if(a&&a.length)a=a;else{c=a||{};a=[]}if(a.length){var d=this,e=a.length;for(b=0;b<a.length;b++)ma(this,a[b],function(){--e==0&&Q(d,c)})}else Q(this,c)};function ma(a,b,c){a.g.loadScript(a.$.buildUrl(a.g.isHttps(),"/"+b+".js"),c)}
function Q(a,b){if(b.userAgent)a.e=(new o(b.userAgent)).parse();b=new ea(a.g,a.j,b);for(var c=new L,d=0;d<a.i.length;d++)a.i[d].addBrowsersToBrowserSet(c);c=N(c,a.e);for(d=0;d<a.i.length;d++)a.i[d].init(a.g);if(c){b.g.appendClassName(b.j,b.l.k(b.m,"loading"));x(b,"loading");na(a,c,b)}else z(b);a.i=[]}
function na(a,b,c){c=new A(a.g,c,{C:function(f){return f.offsetWidth}},a.w,function(){return+new Date});for(var d=0;d<a.i.length;d++){var e=a.i[d];if(e.supportsBrowser(b)){e.load(a.g,c,b,d==a.i.length-1);e.performOptionalActions(window,a.e,a.g)}}}function R(a,b){this.N=a;this.g=b;this.i=[]}R.prototype.v=function(a){this.i.push(a)};
R.prototype.load=function(){var a=this.N.__webfonttypekitmodule__;if(a)for(var b=0;b<this.i.length;b++){var c=this.i[b],d=a[c.getId()];if(d){var e=this.g;d(function(f,i,y){var k=new L;c.addBrowsersToBrowserSet(k);i=[];var n={};if(k=N(k,f)){c.init(e);c.load(e,null,k);for(var w=0;w<c.q.length;w++){var l=c.q[w];i.push(l.t);n[l.t]=l.K[k.getStylesheetFormatId()]||[]}c.performOptionalActions(window,f,e)}y(!!k,i,n)})}}};var S=new L;
S.h(new K("opera","b",function(a,b){if(a=="Opera")return parseFloat(b)>=10.54;return false}));S.h(new K("chrome","b",function(a,b){if(a=="Chrome"){var c=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(b);if(c){a=parseFloat(c[1]);b=parseInt(c[2],10);c=parseInt(c[3],10);if(a>4)return true;else if(a==4&&b>249)return true;else if(a==4&&b==249&&c>=4)return true}}return false}));S.h(new K("ie","c",function(a,b){if(a=="MSIE"){if(a=/([0-9]+.[0-9]+)/.exec(b))return parseFloat(a[1])>=6;return false}}));
S.h(new K("ff35","b",function(a,b,c,d){if(c=="Gecko"){a=/1.9.1b[1-3]{1}/;return/1.9.1/.test(d)&&!a.test(d)}return false}));S.h(new K("ff36","d",function(a,b,c,d){if(c=="Gecko")if(b=/([0-9]+.[0-9]+)(.([0-9]+)|)/.exec(d)){a=parseFloat(b[1]);b=parseInt(b[3],10);return a>1.9||a>=1.9&&b>1}return false}));S.h(new K("safari","b",function(a,b,c,d,e){if(a=="Safari"&&c=="AppleWebKit")if(/Macintosh|Windows/.test(e))if(a=/([0-9]+.[0-9]+)/.exec(d))return parseFloat(a[1])>=525.13;return false}));
if(!window.Typekit){var oa=new J(false,"use.typekit.com","/"),T=(new o(navigator.userAgent)).parse(),U=new H(document,T),V=new P(oa,U,T,document.documentElement,function(a,b){setTimeout(a,b)}),W=new R(window,U);window.Typekit=V;window.Typekit.load=V.load;window.Typekit.addKit=V.v}var X,Y=null,Z,$;X=new J(false,"use.typekit.com","/k");Y=new J(false,function(a){return(a=="https:"?"ssl":"www")+".google-analytics.com"},"");Z=new function(a,b,c){this.G=a;this.L=b;this.Q=c}(null,Y,null);$=new O("olq1epd");
$.ha="3bb2a6e53c9684ffdc9a9bf41f5b2a620f3e55bc4d928e35d4fde98f2fc1346221bf79a4f81c370462a834ec43b5906db1191eafe31b4fb76cffe0a7d4c703d508eb9ba45cabcd097e6f3124925c3ba1334716194e3edd51743c60786f5c1a4fd05c0b52d567148467e00d48208382c9336e3088fb614eb98864685809";$.ca=X;$.u=Z;$.q.push(new I('"myriad-pro-1","myriad-pro-2"',{a:["n3","i3","n6","i6"],b:["n3","i3","n6","i6"],c:["n3","i3","n6","i6"],d:["n3","i3","n6","i6"],f:["n3","i3","n6","i6"]}));
$.A.push(new function(a,b){this.ia=a;this.J=b}([".tk-myriad-pro"],[{value:'"myriad-pro-1","myriad-pro-2",sans-serif',name:"font-family"}]));$.h(M(S,"chrome"));$.h(M(S,"ff35"));$.h(M(S,"ff36"));$.h(M(S,"ie"));$.h(M(S,"opera"));$.h(M(S,"safari"));if(W&&W.N.__webfonttypekitmodule__){W.v($);W.load()}else window.Typekit.addKit($);
})(this,document);